<?php

declare(strict_types=1);

namespace PHPolygon\Scene\Transpiler;

/**
 * Generates a runnable game.php entry for an imported scene, so an import is
 * turnkey: it boots the engine (backend chosen per platform via
 * vio_create('auto', ...)), builds the imported Scene plus a camera framed to
 * the scene's bounds and a daytime sky, then runs.
 *
 * The 3D renderer clears only the depth buffer, so the generated entry always
 * emits a sky (otherwise the colour buffer stays uninitialised), and gives the
 * scene a camera (the importer does not extract three.js cameras).
 */
final class GameEntryGenerator
{
    /**
     * @param array<string, mixed> $import The import.json (name, _scene?, bounds?).
     */
    public function generate(array $import): string
    {
        $name = is_string($import['name'] ?? null) ? $import['name'] : 'imported';
        $class = $this->nameToClassName($name);
        $sceneRef = isset($import['_scene']) && is_string($import['_scene']) ? $import['_scene'] : null;
        $namespace = $sceneRef !== null ? $this->extractNamespace($sceneRef) : 'App\\Scene';
        $fqn = ltrim($namespace . '\\' . $class, '\\');

        $cam = $this->camera(is_array($import['bounds'] ?? null) ? $import['bounds'] : null);

        $tpl = <<<'PHP'
<?php

/**
 * Generated by `phpolygon scene:import` for {{CLASS}} - safe to edit.
 *
 *   php game.php
 *
 * Boots the engine (the GPU backend is chosen per platform), builds the
 * imported scene + a camera framed to it + a sky, then runs.
 */

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use {{FQN}};
use PHPolygon\Component\Camera3DComponent;
use PHPolygon\Component\Transform3D;
use PHPolygon\Engine;
use PHPolygon\EngineConfig;
use PHPolygon\Math\Quaternion;
use PHPolygon\Math\Vec3;
use PHPolygon\Rendering\Color;
use PHPolygon\Rendering\Command\SetSky;
use PHPolygon\Rendering\RenderCommandList;
use PHPolygon\Scene\SceneBuilder;
use PHPolygon\System\Camera3DSystem;
use PHPolygon\System\Renderer3DSystem;
use PHPolygon\System\Transform3DSystem;

const VIEW_W = 1280;
const VIEW_H = 720;

$engine = new Engine(new EngineConfig(
    title:  '{{TITLE}}',
    width:  VIEW_W,
    height: VIEW_H,
    is3D:   true,
    skipSplash: true,
    firstLaunchCalibration: false,
));

$engine->onInit(function () use ($engine): void {
    $builder = new SceneBuilder();

    // The importer does not extract a camera - frame one on the scene bounds.
    $builder->entity('Camera')
        ->with(new Camera3DComponent(fov: 60.0, near: 0.1, far: 500.0, active: true))
        ->with(new Transform3D(
            position: new Vec3({{CAMX}}, {{CAMY}}, {{CAMZ}}),
            rotation: Quaternion::fromAxisAngle(new Vec3(1.0, 0.0, 0.0), {{PITCH}}),
        ));

    (new {{CLASS}}())->build($builder);
    $builder->materialize($engine->world);

    $commandList = $engine->commandList3D ?? new RenderCommandList();
    $engine->world->addSystem(new Transform3DSystem());
    $engine->world->addSystem(new Camera3DSystem($commandList, VIEW_W, VIEW_H));
    $engine->world->addSystem(new Renderer3DSystem($engine->renderer3D, $commandList));
});

// The 3D renderer clears only depth; the colour buffer is filled by the sky,
// re-emitted each frame (Renderer3DSystem clears the command list per frame).
$sky = new SetSky(
    sunDirection: (new Vec3(0.2, 0.85, 0.35))->normalize(),
    sunColor:     new Color(1.0, 0.95, 0.85),
    sunIntensity: 1.0,
    zenithColor:  new Color(0.25, 0.45, 0.85),
    horizonColor: new Color(0.78, 0.86, 0.96),
    groundColor:  new Color(0.30, 0.34, 0.26),
    sunSize:      0.03,
    sunGlowSize:  0.25,
    sunGlowIntensity: 0.4,
    cloudCover:   0.3,
);

$engine->onUpdate(function (Engine $engine) use ($sky): void {
    $engine->commandList3D?->add($sky);
});

$engine->run();

PHP;

        return strtr($tpl, [
            '{{FQN}}'   => $fqn,
            '{{CLASS}}' => $class,
            '{{TITLE}}' => str_replace('\\', '\\\\', str_replace("'", "\\'", $name . ' (PHPolygon import)')),
            '{{CAMX}}'  => $this->float($cam['x']),
            '{{CAMY}}'  => $this->float($cam['y']),
            '{{CAMZ}}'  => $this->float($cam['z']),
            '{{PITCH}}' => $this->float($cam['pitch']),
        ]);
    }

    /**
     * @param array<array-key, mixed>|null $bounds
     * @return array{x: float, y: float, z: float, pitch: float}
     */
    private function camera(?array $bounds): array
    {
        $min = is_array($bounds['min'] ?? null) ? $bounds['min'] : null;
        $max = is_array($bounds['max'] ?? null) ? $bounds['max'] : null;
        if ($min === null || $max === null) {
            return ['x' => 0.0, 'y' => 8.0, 'z' => 14.0, 'pitch' => -0.3];
        }
        $minV = array_map($this->toFloat(...), array_values($min));
        $maxV = array_map($this->toFloat(...), array_values($max));
        $cx = (($minV[0] ?? 0.0) + ($maxV[0] ?? 0.0)) / 2.0;
        return [
            'x' => round($cx, 3),
            'y' => round(($maxV[1] ?? 0.0) + 5.0, 3),
            'z' => round(($maxV[2] ?? 0.0) + 12.0, 3),
            'pitch' => -0.35,
        ];
    }

    private function toFloat(mixed $v): float
    {
        return is_numeric($v) ? (float) $v : 0.0;
    }

    private function float(float $v): string
    {
        $s = (string) $v;
        if (!str_contains($s, '.') && !str_contains($s, 'e') && !str_contains($s, 'E')) {
            $s .= '.0';
        }
        return $s;
    }

    private function nameToClassName(string $name): string
    {
        return str_replace(' ', '', ucwords(str_replace(['_', '-'], ' ', $name)));
    }

    private function extractNamespace(string $fqcn): string
    {
        $pos = strrpos($fqcn, '\\');
        return $pos !== false ? substr($fqcn, 0, $pos) : '';
    }
}
