<?php

declare(strict_types=1);

namespace PHPolygon\Scene\Transpiler;

/**
 * Generates a runnable game.php entry for an imported scene, so an import is
 * turnkey: it boots the engine, builds the imported Scene, registers the
 * scene's systems, emits a sky and runs.
 *
 * Two shapes, chosen from the import's `systems`:
 *  - **Static** (no gameplay systems): frames a camera on the scene bounds and
 *    emits a sky — a viewer for an inert imported scene.
 *  - **Gameplay** (the import carries a PlatformerControllerSystem /
 *    FollowCameraSystem): wires every system from the import with its
 *    constructor dependencies, feeds input, draws a HUD from the
 *    {@see \PHPolygon\Component\PlatformerGameState}, and lets the scene's own
 *    FollowCamera drive the view (no framed camera is injected).
 */
final class GameEntryGenerator
{
    /**
     * Constructor dependencies per engine system, as PHP expressions evaluated
     * inside onInit() (where `$engine` and `$commandList` are in scope).
     *
     * @var array<string, string>
     */
    private const SYSTEM_ARGS = [
        'Transform3DSystem' => '',
        'PlatformerControllerSystem' => '$engine->input',
        'PatrolSystem' => '',
        'StompSystem' => '',
        'CollectibleSystem' => '',
        'GoalSystem' => '',
        'SpinBobSystem' => '',
        'PlatformerAnimationSystem' => '',
        'FollowCameraSystem' => '',
        'Camera3DSystem' => '$commandList, VIEW_W, VIEW_H',
        'Renderer3DSystem' => '$engine->renderer3D, $commandList',
        // --- shooter layer ---
        'ShooterControllerSystem' => '$engine->input, $engine->window',
        'WeaponSystem' => '',
        'ProjectileSystem' => '',
        'DamageSystem' => '',
        'MoverSystem' => '',
        'SpawnerSystem' => '',
    ];

    /** Systems whose presence marks an import as "playable gameplay". */
    private const GAMEPLAY_MARKERS = ['PlatformerControllerSystem', 'FollowCameraSystem'];

    /** Systems whose presence marks an import as a shooter. */
    private const SHOOTER_MARKERS = ['ShooterControllerSystem', 'WeaponSystem', 'SpawnerSystem'];

    /**
     * @param array<string, mixed> $import The import.json (name, _scene?, bounds?, systems?).
     */
    public function generate(array $import): string
    {
        $name = is_string($import['name'] ?? null) ? $import['name'] : 'imported';
        $class = $this->nameToClassName($name);
        $sceneRef = isset($import['_scene']) && is_string($import['_scene']) ? $import['_scene'] : null;
        $namespace = $sceneRef !== null ? $this->extractNamespace($sceneRef) : 'App\\Scene';
        $fqn = ltrim($namespace . '\\' . $class, '\\');
        $title = str_replace('\\', '\\\\', str_replace("'", "\\'", $name . ' (PHPolygon import)'));

        /** @var list<string> $systems */
        $systems = is_array($import['systems'] ?? null) ? array_values(array_filter($import['systems'], 'is_string')) : [];
        if ($this->isShooter($systems)) {
            return $this->generateShooter($fqn, $class, $title, $systems);
        }

        $isGameplay = $this->isGameplay($systems);

        return $isGameplay
            ? $this->generateGameplay($fqn, $class, $title, $systems)
            : $this->generateStatic($fqn, $class, $title, is_array($import['bounds'] ?? null) ? $import['bounds'] : null);
    }

    /** @param list<string> $systems */
    private function isGameplay(array $systems): bool
    {
        foreach ($systems as $s) {
            if (in_array($this->shortName($s), self::GAMEPLAY_MARKERS, true)) {
                return true;
            }
        }
        return false;
    }

    /** @param list<string> $systems */
    private function isShooter(array $systems): bool
    {
        foreach ($systems as $s) {
            if (in_array($this->shortName($s), self::SHOOTER_MARKERS, true)) {
                return true;
            }
        }
        return false;
    }

    /** @param list<string> $systems */
    private function generateGameplay(string $fqn, string $class, string $title, array $systems): string
    {
        // Fall back to a sane default order if the import carries no systems.
        if ($systems === []) {
            $systems = array_map(
                static fn(string $s): string => 'PHPolygon\\System\\' . $s,
                array_keys(self::SYSTEM_ARGS),
            );
        }

        $useSystems = '';
        $registration = '';
        foreach ($systems as $fqcn) {
            $short = $this->shortName($fqcn);
            $useSystems .= "use {$fqcn};\n";
            $args = self::SYSTEM_ARGS[$short] ?? '';
            $registration .= "    \$engine->world->addSystem(new {$short}({$args}));\n";
        }

        $tpl = <<<'PHP'
<?php

/**
 * Generated by `phpolygon scene:import` for {{CLASS}} - safe to edit.
 *
 *   php game.php           (WASD / arrows move, space jumps, R restarts)
 *
 * Boots the engine, builds the imported scene, registers its gameplay systems,
 * and draws a HUD from the PlatformerGameState. The scene's FollowCamera drives
 * the view; the sky fills the colour buffer (the 3D renderer clears only depth).
 * On win / game over the player freezes; [R] rebuilds the scene for a fresh run.
 */

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use {{FQN}};
use PHPolygon\Component\PlatformerGameState;
use PHPolygon\Component\PlatformerStatus;
use PHPolygon\Engine;
use PHPolygon\EngineConfig;
use PHPolygon\Event\SceneLoaded;
use PHPolygon\Math\Vec3;
use PHPolygon\Rendering\Color;
use PHPolygon\Rendering\Command\SetSky;
use PHPolygon\Rendering\RenderCommandList;
use PHPolygon\Scene\SceneBuilder;
{{USE_SYSTEMS}}
const VIEW_W = 1280;
const VIEW_H = 720;

$engine = new Engine(new EngineConfig(
    title:  '{{TITLE}}',
    width:  VIEW_W,
    height: VIEW_H,
    is3D:   true,
    skipSplash: true,
    firstLaunchCalibration: false,
));

// Builds the imported scene into the world. Reused by the restart handler so a
// game over can rebuild a pristine scene without re-registering the systems.
// Emits SceneLoaded so subscribers (e.g., AdaptiveQualityController's warm-up
// reset) get a notification on both the initial boot and every R-restart.
$buildScene = static function (Engine $engine): void {
    $builder = new SceneBuilder();
    $scene = new {{CLASS}}();
    $scene->build($builder);
    $builder->materialize($engine->world);
    $engine->events->dispatch(new SceneLoaded('{{CLASS}}', $scene));
};

$engine->onInit(function () use ($engine, $buildScene): void {
    $buildScene($engine);

    $commandList = $engine->commandList3D ?? new RenderCommandList();
{{REGISTRATION}}});

// The 3D renderer clears only depth; the colour buffer is filled by the sky,
// re-emitted each frame (Renderer3DSystem clears the command list per frame).
$sky = new SetSky(
    sunDirection: (new Vec3(0.2, 0.85, 0.35))->normalize(),
    sunColor:     new Color(1.0, 0.95, 0.85),
    sunIntensity: 1.0,
    zenithColor:  new Color(0.25, 0.45, 0.85),
    horizonColor: new Color(0.78, 0.86, 0.96),
    groundColor:  new Color(0.30, 0.34, 0.26),
    sunSize:      0.03,
    sunGlowSize:  0.25,
    sunGlowIntensity: 0.4,
    cloudCover:   0.3,
);
$engine->onUpdate(function (Engine $engine) use ($sky, $buildScene): void {
    $engine->commandList3D?->add($sky);

    // After win / game over the player is frozen; [R] rebuilds the scene fresh.
    foreach ($engine->world->query(PlatformerGameState::class) as $entity) {
        if ($entity->get(PlatformerGameState::class)->status !== PlatformerStatus::Playing
            && $engine->input->isKeyPressed(82) // GLFW 'R'
        ) {
            $engine->world->clear();
            $buildScene($engine);
            // Restart fires from onUpdate (after this tick's world->update);
            // run an extra 0-dt tick now so Transform3DSystem refreshes every
            // worldMatrix for the freshly-built entities before the same
            // frame's render closure reads them.
            $engine->world->update(0.0);
        }
        break;
    }
});

// HUD: coins / score / lives + win/lose banner, read from PlatformerGameState.
$engine->onRender(function (Engine $engine): void {
    $state = null;
    foreach ($engine->world->query(PlatformerGameState::class) as $entity) {
        $state = $entity->get(PlatformerGameState::class);
        break;
    }
    if ($state === null) {
        return;
    }
    $r = $engine->renderer2D;
    $r->drawText('Coins: ' . str_pad((string) $state->coins, 2, '0', STR_PAD_LEFT), 20.0, 20.0, 22.0, new Color(1.0, 0.82, 0.25));
    $r->drawText('Score: ' . $state->score, 20.0, 50.0, 18.0, new Color(0.6, 0.85, 1.0));
    $r->drawText('Lives: ' . str_repeat('* ', max(0, $state->lives)), 20.0, 74.0, 18.0, new Color(0.9, 0.23, 0.18));

    if ($state->status === PlatformerStatus::Won) {
        $r->drawText('STERN GESCHNAPPT!', VIEW_W / 2.0 - 150.0, VIEW_H / 2.0 - 16.0, 34.0, new Color(1.0, 0.82, 0.25));
        $r->drawText('[R] = Neustart', VIEW_W / 2.0 - 72.0, VIEW_H / 2.0 + 26.0, 18.0, new Color(0.9, 0.95, 1.0));
    } elseif ($state->status === PlatformerStatus::Lost) {
        $r->drawText('GAME OVER', VIEW_W / 2.0 - 90.0, VIEW_H / 2.0 - 16.0, 34.0, new Color(0.9, 0.23, 0.18));
        $r->drawText('[R] = Neustart', VIEW_W / 2.0 - 72.0, VIEW_H / 2.0 + 26.0, 18.0, new Color(0.9, 0.95, 1.0));
    }
});

$engine->run();

PHP;

        return strtr($tpl, [
            '{{FQN}}'         => $fqn,
            '{{CLASS}}'       => $class,
            '{{TITLE}}'       => $title,
            '{{USE_SYSTEMS}}' => rtrim($useSystems, "\n"),
            '{{REGISTRATION}}' => $registration,
        ]);
    }

    /** @param list<string> $systems */
    private function generateShooter(string $fqn, string $class, string $title, array $systems): string
    {
        if ($systems === []) {
            $systems = [
                'PHPolygon\\System\\ShooterControllerSystem',
                'PHPolygon\\System\\WeaponSystem',
                'PHPolygon\\System\\SpawnerSystem',
                'PHPolygon\\System\\MoverSystem',
                'PHPolygon\\System\\ProjectileSystem',
                'PHPolygon\\System\\DamageSystem',
                'PHPolygon\\System\\Transform3DSystem',
                'PHPolygon\\System\\Camera3DSystem',
                'PHPolygon\\System\\Renderer3DSystem',
            ];
        }

        $useSystems = '';
        $registration = '';
        foreach ($systems as $fqcn) {
            $short = $this->shortName($fqcn);
            $useSystems .= "use {$fqcn};\n";
            $args = self::SYSTEM_ARGS[$short] ?? '';
            $registration .= "    \$engine->world->addSystem(new {$short}({$args}));\n";
        }

        $tpl = <<<'PHP'
<?php

/**
 * Generated by `phpolygon scene:import` for {{CLASS}} - safe to edit.
 *
 *   php game.php           (WASD / arrows move, mouse / space fires, R restarts)
 *
 * Boots the engine, builds the imported scene, registers the shooter systems,
 * and draws a HUD from the ShooterGameState. The sky fills the colour buffer
 * (the 3D renderer clears only depth). On game over the run freezes; [R]
 * rebuilds the scene for a fresh run.
 *
 * The importer scaffolds a generic arcade shooter from the prototype's world
 * constants (bounds, the player plane, the enemy-spawn plane) — tune the
 * Spawner / Weapon / enemy stats in the scene to match your design.
 */

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use {{FQN}};
use PHPolygon\Component\Health;
use PHPolygon\Component\ShooterGameState;
use PHPolygon\Component\ShooterStatus;
use PHPolygon\Component\Team;
use PHPolygon\Engine;
use PHPolygon\EngineConfig;
use PHPolygon\Event\SceneLoaded;
use PHPolygon\Math\Vec2;
use PHPolygon\Math\Vec3;
use PHPolygon\Rendering\Color;
use PHPolygon\Rendering\Command\SetSky;
use PHPolygon\Rendering\RenderCommandList;
use PHPolygon\Scene\SceneBuilder;
{{USE_SYSTEMS}}
const VIEW_W = 1280;
const VIEW_H = 720;

$engine = new Engine(new EngineConfig(
    title:  '{{TITLE}}',
    width:  VIEW_W,
    height: VIEW_H,
    is3D:   true,
    skipSplash: true,
    firstLaunchCalibration: false,
));

// Builds the imported scene into the world. Reused by the restart handler so a
// game over can rebuild a pristine scene without re-registering the systems.
$buildScene = static function (Engine $engine): void {
    $builder = new SceneBuilder();
    $scene = new {{CLASS}}();
    $scene->build($builder);
    $builder->materialize($engine->world);
    $engine->events->dispatch(new SceneLoaded('{{CLASS}}', $scene));
};

$engine->onInit(function () use ($engine, $buildScene): void {
    $buildScene($engine);

    $commandList = $engine->commandList3D ?? new RenderCommandList();
{{REGISTRATION}}});

// The 3D renderer clears only depth; the colour buffer is filled by the sky,
// re-emitted each frame (Renderer3DSystem clears the command list per frame).
$sky = new SetSky(
    sunDirection: (new Vec3(0.1, 0.5, 0.85))->normalize(),
    sunColor:     new Color(0.8, 0.9, 1.0),
    sunIntensity: 1.0,
    zenithColor:  new Color(0.02, 0.03, 0.12),
    horizonColor: new Color(0.12, 0.06, 0.28),
    groundColor:  new Color(0.02, 0.02, 0.06),
    sunSize:      0.02,
    sunGlowSize:  0.3,
    sunGlowIntensity: 0.5,
    cloudCover:   0.0,
);
$engine->onUpdate(function (Engine $engine) use ($sky, $buildScene): void {
    $engine->commandList3D?->add($sky);

    // After game over the run is frozen; [R] rebuilds the scene fresh.
    foreach ($engine->world->query(ShooterGameState::class) as $entity) {
        if ($entity->get(ShooterGameState::class)->status !== ShooterStatus::Playing
            && $engine->input->isKeyPressed(82) // GLFW 'R'
        ) {
            $engine->world->clear();
            $buildScene($engine);
            $engine->world->update(0.0);
        }
        break;
    }
});

// HUD: neon crosshair, score panel, player health bar, life pips, and a
// dimmed game-over / win overlay — all read from the scene's ShooterGameState
// and the player's Health. The engine wraps onRender in a 2D frame, so we draw
// straight onto $engine->renderer2D.
$engine->onRender(function (Engine $engine): void {
    $r  = $engine->renderer2D;
    $vw = (float) VIEW_W;
    $vh = (float) VIEW_H;

    $state = null;
    foreach ($engine->world->query(ShooterGameState::class) as $entity) {
        $state = $entity->get(ShooterGameState::class);
        break;
    }
    $playing = $state === null || $state->status === ShooterStatus::Playing;

    // Crosshair (hidden once the run ends).
    if ($playing) {
        $cx = $vw / 2.0;
        $cy = $vh / 2.0;
        $tint = new Color(0.6, 0.95, 1.0, 0.9);
        $r->drawLine(new Vec2($cx - 13.0, $cy), new Vec2($cx - 5.0, $cy), $tint, 2.0);
        $r->drawLine(new Vec2($cx + 5.0, $cy), new Vec2($cx + 13.0, $cy), $tint, 2.0);
        $r->drawLine(new Vec2($cx, $cy - 13.0), new Vec2($cx, $cy - 5.0), $tint, 2.0);
        $r->drawLine(new Vec2($cx, $cy + 5.0), new Vec2($cx, $cy + 13.0), $tint, 2.0);
        $r->drawCircleOutline($cx, $cy, 2.0, $tint, 1.5);
    }

    if ($state === null) {
        return;
    }

    // Player health (first Player-team combatant).
    $hp = 0;
    $maxHp = 0;
    foreach ($engine->world->query(Health::class) as $entity) {
        $hc = $entity->get(Health::class);
        if ($hc->team === Team::Player) {
            $hp = $hc->hp;
            $maxHp = $hc->maxHp;
            break;
        }
    }

    // Top-left stat panel: score + health bar.
    $r->drawRoundedRect(16.0, 16.0, 244.0, 96.0, 10.0, new Color(0.04, 0.06, 0.12, 0.72));
    $r->drawRoundedRectOutline(16.0, 16.0, 244.0, 96.0, 10.0, new Color(0.3, 0.8, 1.0, 0.5), 1.5);
    $r->drawText('SCORE', 30.0, 28.0, 12.0, new Color(0.45, 0.62, 0.72));
    $r->drawText(str_pad((string) $state->score, 6, '0', STR_PAD_LEFT), 30.0, 44.0, 26.0, new Color(0.72, 0.97, 1.0));

    $barX = 30.0;
    $barY = 90.0;
    $barW = 216.0;
    $barH = 10.0;
    $r->drawRoundedRect($barX, $barY, $barW, $barH, 5.0, new Color(0.16, 0.06, 0.12, 0.9));
    if ($maxHp > 0 && $hp > 0) {
        $frac = max(0.0, min(1.0, $hp / $maxHp));
        $col = $frac > 0.5
            ? new Color(0.3, 0.95, 0.7)
            : ($frac > 0.25 ? new Color(1.0, 0.8, 0.3) : new Color(1.0, 0.3, 0.4));
        $r->drawRoundedRect($barX, $barY, max(5.0, $barW * $frac), $barH, 5.0, $col);
    }

    // Lives — neon pips, top-right.
    for ($i = 0; $i < max(0, $state->lives); $i++) {
        $lx = $vw - 30.0 - $i * 26.0;
        $r->drawCircle($lx, 32.0, 8.0, new Color(1.0, 0.35, 0.6));
        $r->drawCircleOutline($lx, 32.0, 8.0, new Color(1.0, 0.75, 0.88, 0.85), 1.5);
    }

    // Wave counter, top-centre.
    if ($state->wave > 0) {
        $r->drawTextCentered('WAVE ' . $state->wave, $vw / 2.0, 30.0, 16.0, new Color(0.6, 0.82, 0.96, 0.85));
    }

    // Game-over / win overlay.
    if (!$playing) {
        $won = $state->status === ShooterStatus::Won;
        $accent = $won ? new Color(0.5, 1.0, 0.72) : new Color(1.0, 0.32, 0.46);
        $r->drawRect(0.0, 0.0, $vw, $vh, new Color(0.02, 0.02, 0.06, 0.62));

        $pw = 440.0;
        $ph = 210.0;
        $px = ($vw - $pw) / 2.0;
        $py = ($vh - $ph) / 2.0;
        $r->drawRoundedRect($px, $py, $pw, $ph, 16.0, new Color(0.05, 0.07, 0.14, 0.96));
        $r->drawRoundedRectOutline($px, $py, $pw, $ph, 16.0, $accent, 2.0);
        $r->drawTextCentered($won ? 'SIEG!' : 'GAME OVER', $vw / 2.0, $py + 62.0, 44.0, $accent);
        $r->drawTextCentered('Score  ' . str_pad((string) $state->score, 6, '0', STR_PAD_LEFT), $vw / 2.0, $py + 116.0, 22.0, new Color(0.72, 0.9, 1.0));
        $r->drawTextCentered('[ R ]  Neustart', $vw / 2.0, $py + 158.0, 18.0, new Color(0.55, 0.68, 0.8));
    }
});

$engine->run();

PHP;

        return strtr($tpl, [
            '{{FQN}}'          => $fqn,
            '{{CLASS}}'        => $class,
            '{{TITLE}}'        => $title,
            '{{USE_SYSTEMS}}'  => rtrim($useSystems, "\n"),
            '{{REGISTRATION}}' => $registration,
        ]);
    }

    /**
     * @param array<array-key, mixed>|null $bounds
     */
    private function generateStatic(string $fqn, string $class, string $title, ?array $bounds): string
    {
        $cam = $this->camera($bounds);

        $tpl = <<<'PHP'
<?php

/**
 * Generated by `phpolygon scene:import` for {{CLASS}} - safe to edit.
 *
 *   php game.php
 *
 * Boots the engine (the GPU backend is chosen per platform), builds the
 * imported scene + a camera framed to it + a sky, then runs.
 */

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use {{FQN}};
use PHPolygon\Component\Camera3DComponent;
use PHPolygon\Component\Transform3D;
use PHPolygon\Engine;
use PHPolygon\EngineConfig;
use PHPolygon\Math\Quaternion;
use PHPolygon\Math\Vec3;
use PHPolygon\Rendering\Color;
use PHPolygon\Rendering\Command\SetSky;
use PHPolygon\Rendering\RenderCommandList;
use PHPolygon\Scene\SceneBuilder;
use PHPolygon\System\Camera3DSystem;
use PHPolygon\System\Renderer3DSystem;
use PHPolygon\System\Transform3DSystem;

const VIEW_W = 1280;
const VIEW_H = 720;

$engine = new Engine(new EngineConfig(
    title:  '{{TITLE}}',
    width:  VIEW_W,
    height: VIEW_H,
    is3D:   true,
    skipSplash: true,
    firstLaunchCalibration: false,
));

$engine->onInit(function () use ($engine): void {
    $builder = new SceneBuilder();

    // The importer does not extract a camera - frame one on the scene bounds.
    $builder->entity('Camera')
        ->with(new Camera3DComponent(fov: 60.0, near: 0.1, far: 500.0, active: true))
        ->with(new Transform3D(
            position: new Vec3({{CAMX}}, {{CAMY}}, {{CAMZ}}),
            rotation: Quaternion::fromAxisAngle(new Vec3(1.0, 0.0, 0.0), {{PITCH}}),
        ));

    (new {{CLASS}}())->build($builder);
    $builder->materialize($engine->world);

    $commandList = $engine->commandList3D ?? new RenderCommandList();
    $engine->world->addSystem(new Transform3DSystem());
    $engine->world->addSystem(new Camera3DSystem($commandList, VIEW_W, VIEW_H));
    $engine->world->addSystem(new Renderer3DSystem($engine->renderer3D, $commandList));
});

// The 3D renderer clears only depth; the colour buffer is filled by the sky,
// re-emitted each frame (Renderer3DSystem clears the command list per frame).
$sky = new SetSky(
    sunDirection: (new Vec3(0.2, 0.85, 0.35))->normalize(),
    sunColor:     new Color(1.0, 0.95, 0.85),
    sunIntensity: 1.0,
    zenithColor:  new Color(0.25, 0.45, 0.85),
    horizonColor: new Color(0.78, 0.86, 0.96),
    groundColor:  new Color(0.30, 0.34, 0.26),
    sunSize:      0.03,
    sunGlowSize:  0.25,
    sunGlowIntensity: 0.4,
    cloudCover:   0.3,
);

$engine->onUpdate(function (Engine $engine) use ($sky): void {
    $engine->commandList3D?->add($sky);
});

$engine->run();

PHP;

        return strtr($tpl, [
            '{{FQN}}'   => $fqn,
            '{{CLASS}}' => $class,
            '{{TITLE}}' => $title,
            '{{CAMX}}'  => $this->float($cam['x']),
            '{{CAMY}}'  => $this->float($cam['y']),
            '{{CAMZ}}'  => $this->float($cam['z']),
            '{{PITCH}}' => $this->float($cam['pitch']),
        ]);
    }

    /**
     * @param array<array-key, mixed>|null $bounds
     * @return array{x: float, y: float, z: float, pitch: float}
     */
    private function camera(?array $bounds): array
    {
        $min = is_array($bounds['min'] ?? null) ? $bounds['min'] : null;
        $max = is_array($bounds['max'] ?? null) ? $bounds['max'] : null;
        if ($min === null || $max === null) {
            return ['x' => 0.0, 'y' => 8.0, 'z' => 14.0, 'pitch' => -0.3];
        }
        $minV = array_map($this->toFloat(...), array_values($min));
        $maxV = array_map($this->toFloat(...), array_values($max));
        $cx = (($minV[0] ?? 0.0) + ($maxV[0] ?? 0.0)) / 2.0;
        return [
            'x' => round($cx, 3),
            'y' => round(($maxV[1] ?? 0.0) + 5.0, 3),
            'z' => round(($maxV[2] ?? 0.0) + 12.0, 3),
            'pitch' => -0.35,
        ];
    }

    private function toFloat(mixed $v): float
    {
        return is_numeric($v) ? (float) $v : 0.0;
    }

    private function float(float $v): string
    {
        $s = (string) $v;
        if (!str_contains($s, '.') && !str_contains($s, 'e') && !str_contains($s, 'E')) {
            $s .= '.0';
        }
        return $s;
    }

    private function shortName(string $fqcn): string
    {
        $parts = explode('\\', $fqcn);
        return end($parts);
    }

    private function nameToClassName(string $name): string
    {
        return str_replace(' ', '', ucwords(str_replace(['_', '-'], ' ', $name)));
    }

    private function extractNamespace(string $fqcn): string
    {
        $pos = strrpos($fqcn, '\\');
        return $pos !== false ? substr($fqcn, 0, $pos) : '';
    }
}
