<?php

declare(strict_types=1);

namespace PHPolygon\Tests\Scene;

use PHPolygon\Component\MeshRenderer;
use PHPolygon\Component\Transform3D;
use PHPolygon\ECS\AbstractComponent;
use PHPolygon\ECS\Attribute\Property;
use PHPolygon\ECS\Attribute\Serializable;
use PHPolygon\ECS\World;
use PHPolygon\Math\Vec3;
use PHPolygon\Scene\EntityDeclaration;
use PHPolygon\Scene\Prefab;
use PHPolygon\Scene\PrefabRegistry;
use PHPolygon\Scene\Scene;
use PHPolygon\Scene\SceneBuilder;
use PHPolygon\Scene\Transpiler\ComponentOverrides;
use PHPolygon\Scene\Transpiler\JsonSceneLoader;
use PHPolygon\Scene\Transpiler\SceneTranspiler;
use PHPUnit\Framework\TestCase;

/**
 * The prefab reference + authored-input pipeline: a prefab is placed with a
 * design-variant component as build() INPUT, its geometry is regenerated by
 * build() (never serialized), and a scene round-trips as a prefab reference plus
 * only the authored overrides — the sibling geometry the prefab emits is skipped.
 */
final class PrefabPipelineTest extends TestCase
{
    private function registry(): PrefabRegistry
    {
        $registry = new PrefabRegistry();
        $registry->register(GadgetPrefab::class);

        return $registry;
    }

    /** Find a declaration by name in the builder. */
    private function decl(SceneBuilder $b, string $name): ?EntityDeclaration
    {
        foreach ($b->getDeclarations() as $d) {
            if ($d->getName() === $name) {
                return $d;
            }
        }

        return null;
    }

    private function componentOf(EntityDeclaration $decl, string $class): ?object
    {
        foreach ($decl->getComponents() as $c) {
            if ($c instanceof $class) {
                return $c;
            }
        }

        return null;
    }

    // ── SceneBuilder::prefabInstance ─────────────────────────────────────────

    public function testPrefabInstanceTagsRecordsAuthoredAndMarksSiblings(): void
    {
        $b = new SceneBuilder();
        $decl = $b->prefabInstance(
            (new GadgetPrefab())->at(new Vec3(3.0, 0.0, -4.0))->withAuthored(new GadgetDesign('b')),
            'Gadget_1',
        );

        // The returned declaration is the anchor: named, prefab-tagged.
        self::assertSame('Gadget_1', $decl->getName());
        self::assertSame(GadgetPrefab::class, $decl->getPrefabSource());

        // build() read the authored variant as INPUT (drives the sibling's mesh).
        $part = $this->decl($b, 'Gadget_1_Part');
        self::assertNotNull($part);
        $mesh = $this->componentOf($part, MeshRenderer::class);
        self::assertInstanceOf(MeshRenderer::class, $mesh);
        self::assertSame('mesh.gadget.b', $mesh->meshId);

        // The sibling part is flagged prefab-generated; the anchor is not.
        self::assertTrue($part->isGeneratedByPrefab());
        self::assertFalse($decl->isGeneratedByPrefab());

        // Authored input recorded for serialization = placement + variant only.
        $authored = $decl->getPrefabAuthored();
        self::assertNotNull($authored);
        $classes = array_map(static fn (object $c): string => $c::class, $authored);
        self::assertContains(Transform3D::class, $classes);
        self::assertContains(GadgetDesign::class, $classes);
        self::assertNotContains(MeshRenderer::class, $classes);
    }

    public function testPrefabByNameResolvesThroughRegistry(): void
    {
        $b = new SceneBuilder();
        $b->setPrefabRegistry($this->registry());

        $decl = $b->prefabByName('Gadget', 'Gadget_2');

        self::assertSame('Gadget_2', $decl->getName());
        self::assertSame(GadgetPrefab::class, $decl->getPrefabSource());
    }

    // ── EntityDeclaration::withOverride + ComponentOverrides ─────────────────

    public function testWithOverrideReplacesSameClass(): void
    {
        $decl = (new SceneBuilder())->entity('e')
            ->with(new GadgetDesign('a'))
            ->withOverride(new GadgetDesign('c'));

        $designs = array_filter($decl->getComponents(), static fn (object $c): bool => $c instanceof GadgetDesign);
        self::assertCount(1, $designs);
        self::assertSame('c', array_values($designs)[0]->variant);
    }

    public function testApplyByClassReplacesAndAppends(): void
    {
        $decl = (new SceneBuilder())->entity('e')->with(new GadgetDesign('a'));
        ComponentOverrides::applyByClass($decl, [new GadgetDesign('z'), new Transform3D(new Vec3(1, 2, 3))]);

        $designs = array_values(array_filter($decl->getComponents(), static fn (object $c): bool => $c instanceof GadgetDesign));
        self::assertCount(1, $designs);
        self::assertSame('z', $designs[0]->variant);
        self::assertInstanceOf(Transform3D::class, $this->componentOf($decl, Transform3D::class));
    }

    // ── JsonSceneLoader ──────────────────────────────────────────────────────

    public function testLoaderRebuildsGeometryFromAuthoredInput(): void
    {
        $json = [
            'entities' => [
                [
                    'name' => 'Gadget_1',
                    'prefab' => GadgetPrefab::class,
                    'components' => [
                        ['_class' => GadgetDesign::class, 'variant' => 'b'],
                        ['_class' => Transform3D::class, 'position' => ['x' => 3.0, 'y' => 0.0, 'z' => -4.0]],
                    ],
                ],
            ],
        ];

        $b = new SceneBuilder();
        (new JsonSceneLoader())->load($b, $json, $this->registry());
        $world = new World();
        $map = $b->materialize($world);

        // Anchor + regenerated sibling geometry both exist.
        self::assertArrayHasKey('Gadget_1', $map);
        self::assertArrayHasKey('Gadget_1_Part', $map);

        // Variant drove the regenerated geometry, and rides on the anchor.
        $partMesh = $world->getComponent($map['Gadget_1_Part'], MeshRenderer::class);
        self::assertInstanceOf(MeshRenderer::class, $partMesh);
        self::assertSame('mesh.gadget.b', $partMesh->meshId);
        $design = $world->getComponent($map['Gadget_1'], GadgetDesign::class);
        self::assertInstanceOf(GadgetDesign::class, $design);
        self::assertSame('b', $design->variant);

        // Placement fed the ground point (anchor transform came from build()).
        $t = $world->getComponent($map['Gadget_1'], Transform3D::class);
        self::assertInstanceOf(Transform3D::class, $t);
        self::assertEqualsWithDelta(3.0, $t->position->x, 1e-6);
        self::assertEqualsWithDelta(-4.0, $t->position->z, 1e-6);
    }

    // ── SceneTranspiler round-trip ───────────────────────────────────────────

    private function gadgetScene(): Scene
    {
        return new class extends Scene {
            public function getName(): string
            {
                return 'gadget_fixture';
            }

            public function build(SceneBuilder $builder): void
            {
                $builder->prefabInstance(
                    (new GadgetPrefab())->at(new Vec3(3.0, 0.0, -4.0))->withAuthored(new GadgetDesign('b')),
                    'Gadget_1',
                );
            }
        };
    }

    public function testTranspilerSerializesReferencePlusAuthoredOnly(): void
    {
        $data = (new SceneTranspiler())->toArray($this->gadgetScene());
        $entities = $data['entities'];

        // Sibling geometry is skipped; only the anchor reference is serialized.
        self::assertCount(1, $entities);
        self::assertSame(GadgetPrefab::class, $entities[0]['prefab']);

        $classes = array_map(static fn (array $c): mixed => $c['_class'] ?? null, $entities[0]['components']);
        self::assertContains(Transform3D::class, $classes);
        self::assertContains(GadgetDesign::class, $classes);
        self::assertNotContains(MeshRenderer::class, $classes);
    }

    public function testTranspilerRoundTripReproducesLiveWorld(): void
    {
        $data = (new SceneTranspiler())->toArray($this->gadgetScene());

        $b = new SceneBuilder();
        (new JsonSceneLoader())->load($b, $data, $this->registry());
        $world = new World();
        $map = $b->materialize($world);

        self::assertArrayHasKey('Gadget_1', $map);
        self::assertArrayHasKey('Gadget_1_Part', $map);
        $design = $world->getComponent($map['Gadget_1'], GadgetDesign::class);
        self::assertInstanceOf(GadgetDesign::class, $design);
        self::assertSame('b', $design->variant);
    }

    public function testCodegenEmitsPrefabInstanceWithoutGeometry(): void
    {
        $transpiler = new SceneTranspiler();
        $php = $transpiler->fromArray($transpiler->toArray($this->gadgetScene()));

        self::assertStringContainsString('->prefabInstance(', $php);
        self::assertStringContainsString('new GadgetPrefab()', $php);
        self::assertStringContainsString('->at(new Vec3(', $php);
        self::assertStringContainsString('->withAuthored(', $php);
        self::assertStringNotContainsString('MeshRenderer', $php);
    }
}

/**
 * A design-variant marker: authored input a prefab reads to pick its geometry.
 *
 * @internal
 */
#[Serializable]
final class GadgetDesign extends AbstractComponent
{
    #[Property]
    public string $variant = 'a';

    public function __construct(string $variant = 'a')
    {
        $this->variant = $variant;
    }
}

/**
 * A prefab that emits an anchor plus a separate geometry part whose mesh is
 * chosen by the authored {@see GadgetDesign} variant — the geometry is produced
 * here in PHP, never serialized.
 *
 * @internal
 */
final class GadgetPrefab extends Prefab
{
    public static function getName(): string
    {
        return 'Gadget';
    }

    public function build(SceneBuilder $builder): EntityDeclaration
    {
        $variant = 'a';
        foreach ($this->getAuthored() as $component) {
            if ($component instanceof GadgetDesign) {
                $variant = $component->variant;
            }
        }

        // Sibling geometry part (flat, in world space) — flagged prefab-generated.
        $builder->entity($this->getInstanceName() . '_Part')
            ->with(new Transform3D(position: $this->getPosition()))
            ->with(new MeshRenderer("mesh.gadget.{$variant}", 'mat.gadget'));

        // Anchor (the returned declaration).
        return $builder->entity($this->getInstanceName())
            ->with(new Transform3D(
                position: $this->getPosition(),
                rotation: $this->getRotation(),
                scale: $this->getScale(),
            ))
            ->with(new MeshRenderer('mesh.gadget.body', 'mat.gadget'));
    }
}
