#!/usr/bin/env node
// Generates the typed component vocabulary from the exported schema.json.
//
//   node scripts/generate.mjs [path/to/schema.json]
//
// Reads the schema written by `bin/phpolygon prototype:export` and emits:
//   src/generated/components.ts  - prop interfaces + COMPONENT_META + ComponentName
//   src/generated/builders.ts     - one typed factory per component
//
// The vocabulary is DERIVED FROM PHP, so it cannot drift from the engine's
// component set. Re-run after every prototype:export (npm run gen).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const schemaPath = resolve(process.argv[2] ?? `${root}/public/bundle/schema.json`)
const outDir = `${root}/src/generated`

const schema = JSON.parse(readFileSync(schemaPath, 'utf8'))
const components = schema.components ?? {}
const names = Object.keys(components).sort()

const HEADER = `// AUTO-GENERATED by scripts/generate.mjs from the exported schema.json.\n// Do not edit by hand - run \`npm run gen\` after \`prototype:export\`.\n`

function tsType(prop) {
  switch (prop.type) {
    case 'Vec2': return 'Vec2Input'
    case 'Vec3': return 'Vec3Input'
    case 'Vec4': return 'Vec4Input'
    case 'Quaternion': return 'QuatInput'
    case 'Color': return 'ColorInput'
    case 'Rect': return 'RectInput'
    case 'Mat3':
    case 'Mat4': return 'number[]'
    case 'int':
    case 'float': return 'number'
    case 'bool': return 'boolean'
    case 'string': return 'string'
    case 'enum': {
      const literals = (prop.enum ?? []).map((v) => (typeof v === 'string' ? JSON.stringify(v) : String(v)))
      return literals.length > 0 ? literals.join(' | ') : 'never'
    }
    case 'array': return 'unknown[]'
    case 'object': return 'Record<string, unknown>'
    default: return 'unknown'
  }
}

// --- components.ts ---
let comp = HEADER
comp += `import type { Vec2Input, Vec3Input, Vec4Input, QuatInput, ColorInput, RectInput } from '../authoring/inputs'\n\n`

for (const name of names) {
  const def = components[name]
  comp += `export interface ${name}Props {\n`
  for (const prop of def.properties ?? []) {
    let t = tsType(prop)
    if (prop.nullable) t += ' | null'
    comp += `  ${prop.name}?: ${t}\n`
  }
  comp += `}\n\n`
}

comp += `export type ComponentName =\n  ${names.map((n) => `'${n}'`).join('\n  | ')}\n\n`

comp += `export interface ComponentMeta {\n`
comp += `  class: string\n`
comp += `  properties: { name: string; type: string; phpType?: string; nullable?: boolean }[]\n`
comp += `  defaults: Record<string, unknown>\n`
comp += `}\n\n`

const meta = {}
for (const name of names) {
  const def = components[name]
  meta[name] = {
    class: def.class,
    properties: (def.properties ?? []).map((p) => ({
      name: p.name,
      type: p.type,
      ...(p.phpType ? { phpType: p.phpType } : {}),
      ...(p.nullable ? { nullable: true } : {}),
    })),
    defaults: def.defaults ?? {},
  }
}
comp += `export const COMPONENT_META: Record<ComponentName, ComponentMeta> = ${JSON.stringify(meta, null, 2)} as const\n`

// --- builders.ts ---
let build = HEADER
build += `import type { ComponentJson } from '../runtime/types'\n`
build += `import { buildComponent } from '../authoring/dsl'\n`
build += `import type {\n${names.map((n) => `  ${n}Props,`).join('\n')}\n} from './components'\n\n`
for (const name of names) {
  build += `export const ${name} = (props: ${name}Props = {}): ComponentJson => buildComponent('${name}', props)\n`
}

mkdirSync(outDir, { recursive: true })
writeFileSync(`${outDir}/components.ts`, comp)
writeFileSync(`${outDir}/builders.ts`, build)

console.log(`Generated ${names.length} components -> src/generated/{components,builders}.ts`)
